//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asf.Taxi.BusinessLogic.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asf.Taxi.BusinessLogic.Localization.EnumDescriptions", typeof(EnumDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergenza.
        /// </summary>
        public static string AllarmTypes_Emergency {
            get {
                return ResourceManager.GetString("AllarmTypes_Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento.
        /// </summary>
        public static string AllarmTypes_Event {
            get {
                return ResourceManager.GetString("AllarmTypes_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiera.
        /// </summary>
        public static string AllarmTypes_Expo {
            get {
                return ResourceManager.GetString("AllarmTypes_Expo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno.
        /// </summary>
        public static string AllarmTypes_Turn {
            get {
                return ResourceManager.GetString("AllarmTypes_Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BioFuels.
        /// </summary>
        public static string CarFuelTypes_BioFuels {
            get {
                return ResourceManager.GetString("CarFuelTypes_BioFuels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metano.
        /// </summary>
        public static string CarFuelTypes_CompressedNaturalGas {
            get {
                return ResourceManager.GetString("CarFuelTypes_CompressedNaturalGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        public static string CarFuelTypes_Diesel {
            get {
                return ResourceManager.GetString("CarFuelTypes_Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elettrica.
        /// </summary>
        public static string CarFuelTypes_Electric {
            get {
                return ResourceManager.GetString("CarFuelTypes_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benzina.
        /// </summary>
        public static string CarFuelTypes_Gasoline {
            get {
                return ResourceManager.GetString("CarFuelTypes_Gasoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibrida.
        /// </summary>
        public static string CarFuelTypes_Hybrid {
            get {
                return ResourceManager.GetString("CarFuelTypes_Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idrogeno.
        /// </summary>
        public static string CarFuelTypes_Hydrogen {
            get {
                return ResourceManager.GetString("CarFuelTypes_Hydrogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPL.
        /// </summary>
        public static string CarFuelTypes_LiquefiedPetroleumGas {
            get {
                return ResourceManager.GetString("CarFuelTypes_LiquefiedPetroleumGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creata.
        /// </summary>
        public static string LicenseeStatus_Created {
            get {
                return ResourceManager.GetString("LicenseeStatus_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attiva.
        /// </summary>
        public static string LicenseeStatus_Released {
            get {
                return ResourceManager.GetString("LicenseeStatus_Released", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sospesa.
        /// </summary>
        public static string LicenseeStatus_Suspended {
            get {
                return ResourceManager.GetString("LicenseeStatus_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminata.
        /// </summary>
        public static string LicenseeStatus_Terminated {
            get {
                return ResourceManager.GetString("LicenseeStatus_Terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCC_Auto.
        /// </summary>
        public static string LicenseeTypes_NCC_Auto {
            get {
                return ResourceManager.GetString("LicenseeTypes_NCC_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NCC_Bus.
        /// </summary>
        public static string LicenseeTypes_NCC_Bus {
            get {
                return ResourceManager.GetString("LicenseeTypes_NCC_Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxi.
        /// </summary>
        public static string LicenseeTypes_Taxi {
            get {
                return ResourceManager.GetString("LicenseeTypes_Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanzione disciplinare.
        /// </summary>
        public static string MeasureTypes_Disciplinary {
            get {
                return ResourceManager.GetString("MeasureTypes_Disciplinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multa.
        /// </summary>
        public static string MeasureTypes_Fine {
            get {
                return ResourceManager.GetString("MeasureTypes_Fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segnalazione.
        /// </summary>
        public static string MeasureTypes_Report {
            get {
                return ResourceManager.GetString("MeasureTypes_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accettata.
        /// </summary>
        public static string RequestStatus_Accepted {
            get {
                return ResourceManager.GetString("RequestStatus_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annullata.
        /// </summary>
        public static string RequestStatus_Canceled {
            get {
                return ResourceManager.GetString("RequestStatus_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rifiutata.
        /// </summary>
        public static string RequestStatus_Rejected {
            get {
                return ResourceManager.GetString("RequestStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inoltrata.
        /// </summary>
        public static string RequestStatus_Submitted {
            get {
                return ResourceManager.GetString("RequestStatus_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sostituzione alla guida.
        /// </summary>
        public static string RequestTypes_DriverSubstitution {
            get {
                return ResourceManager.GetString("RequestTypes_DriverSubstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferie.
        /// </summary>
        public static string RequestTypes_Holiday {
            get {
                return ResourceManager.GetString("RequestTypes_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altro.
        /// </summary>
        public static string RequestTypes_Other {
            get {
                return ResourceManager.GetString("RequestTypes_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Malattia.
        /// </summary>
        public static string RequestTypes_Sickness {
            get {
                return ResourceManager.GetString("RequestTypes_Sickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermo macchina.
        /// </summary>
        public static string RequestTypes_VehicleStop {
            get {
                return ResourceManager.GetString("RequestTypes_VehicleStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5+1.
        /// </summary>
        public static string ShiftTypes__5Plus1 {
            get {
                return ResourceManager.GetString("ShiftTypes__5Plus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7+1.
        /// </summary>
        public static string ShiftTypes__7Plus1 {
            get {
                return ResourceManager.GetString("ShiftTypes__7Plus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborazione familiare di tipo 5 + 1.
        /// </summary>
        public static string ShiftTypes_CollaborazioneFamiliare_5Plus1 {
            get {
                return ResourceManager.GetString("ShiftTypes_CollaborazioneFamiliare_5Plus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborazione familiare di tipo 7 + 1.
        /// </summary>
        public static string ShiftTypes_CollaborazioneFamiliare_7Plus1 {
            get {
                return ResourceManager.GetString("ShiftTypes_CollaborazioneFamiliare_7Plus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborazione familiare di tipo colorato.
        /// </summary>
        public static string ShiftTypes_CollaborazioneFamiliare_Colorato {
            get {
                return ResourceManager.GetString("ShiftTypes_CollaborazioneFamiliare_Colorato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colorato.
        /// </summary>
        public static string ShiftTypes_Colorato {
            get {
                return ResourceManager.GetString("ShiftTypes_Colorato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciale.
        /// </summary>
        public static string ShiftTypes_Speciale {
            get {
                return ResourceManager.GetString("ShiftTypes_Speciale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string SubShiftTypes__1 {
            get {
                return ResourceManager.GetString("SubShiftTypes__1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string SubShiftTypes__2 {
            get {
                return ResourceManager.GetString("SubShiftTypes__2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21.
        /// </summary>
        public static string SubShiftTypes__21 {
            get {
                return ResourceManager.GetString("SubShiftTypes__21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        public static string SubShiftTypes__22 {
            get {
                return ResourceManager.GetString("SubShiftTypes__22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23.
        /// </summary>
        public static string SubShiftTypes__23 {
            get {
                return ResourceManager.GetString("SubShiftTypes__23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24.
        /// </summary>
        public static string SubShiftTypes__24 {
            get {
                return ResourceManager.GetString("SubShiftTypes__24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        public static string SubShiftTypes__25 {
            get {
                return ResourceManager.GetString("SubShiftTypes__25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26.
        /// </summary>
        public static string SubShiftTypes__26 {
            get {
                return ResourceManager.GetString("SubShiftTypes__26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string SubShiftTypes__3 {
            get {
                return ResourceManager.GetString("SubShiftTypes__3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string SubShiftTypes__4 {
            get {
                return ResourceManager.GetString("SubShiftTypes__4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        public static string SubShiftTypes__5 {
            get {
                return ResourceManager.GetString("SubShiftTypes__5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        public static string SubShiftTypes__6 {
            get {
                return ResourceManager.GetString("SubShiftTypes__6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        public static string SubShiftTypes__7 {
            get {
                return ResourceManager.GetString("SubShiftTypes__7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        public static string SubShiftTypes__8 {
            get {
                return ResourceManager.GetString("SubShiftTypes__8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string SubShiftTypes_Blue {
            get {
                return ResourceManager.GetString("SubShiftTypes_Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verde.
        /// </summary>
        public static string SubShiftTypes_Green {
            get {
                return ResourceManager.GetString("SubShiftTypes_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senza sottoturno.
        /// </summary>
        public static string SubShiftTypes_NOSub {
            get {
                return ResourceManager.GetString("SubShiftTypes_NOSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosso A.
        /// </summary>
        public static string SubShiftTypes_Red_A {
            get {
                return ResourceManager.GetString("SubShiftTypes_Red_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosso B.
        /// </summary>
        public static string SubShiftTypes_Red_B {
            get {
                return ResourceManager.GetString("SubShiftTypes_Red_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosso C.
        /// </summary>
        public static string SubShiftTypes_Red_C {
            get {
                return ResourceManager.GetString("SubShiftTypes_Red_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosso dispari.
        /// </summary>
        public static string SubShiftTypes_Red_Odd {
            get {
                return ResourceManager.GetString("SubShiftTypes_Red_Odd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bianco pari.
        /// </summary>
        public static string SubShiftTypes_White_Even {
            get {
                return ResourceManager.GetString("SubShiftTypes_White_Even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bianco X.
        /// </summary>
        public static string SubShiftTypes_White_X {
            get {
                return ResourceManager.GetString("SubShiftTypes_White_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bianco Y.
        /// </summary>
        public static string SubShiftTypes_White_Y {
            get {
                return ResourceManager.GetString("SubShiftTypes_White_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bianco Z.
        /// </summary>
        public static string SubShiftTypes_White_Z {
            get {
                return ResourceManager.GetString("SubShiftTypes_White_Z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine stacco.
        /// </summary>
        public static string TimestampTypes_EndPause {
            get {
                return ResourceManager.GetString("TimestampTypes_EndPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine turno.
        /// </summary>
        public static string TimestampTypes_EndShift {
            get {
                return ResourceManager.GetString("TimestampTypes_EndShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizio stacco.
        /// </summary>
        public static string TimestampTypes_StartPause {
            get {
                return ResourceManager.GetString("TimestampTypes_StartPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizio turno.
        /// </summary>
        public static string TimestampTypes_StartShift {
            get {
                return ResourceManager.GetString("TimestampTypes_StartShift", resourceCulture);
            }
        }
    }
}
