//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asf.Taxi.BusinessLogic.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asf.Taxi.BusinessLogic.Localization.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Già associato ad un altra licenza.
        /// </summary>
        public static string AlreadyAssociatedToOtherLicensee {
            get {
                return ResourceManager.GetString("AlreadyAssociatedToOtherLicensee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questa persona è già proprietaria di licenza attiva.
        /// </summary>
        public static string AlreadyAssociatedToOtherOwner {
            get {
                return ResourceManager.GetString("AlreadyAssociatedToOtherOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato specificato nessun contenuto per l&apos;allegato..
        /// </summary>
        public static string Attachment_ContentIsMandatory {
            get {
                return ResourceManager.GetString("Attachment_ContentIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il contenuto del file è obbligatorio..
        /// </summary>
        public static string AttachmentContentIsMandatory {
            get {
                return ResourceManager.GetString("AttachmentContentIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il processo di recupero dello stato della email..
        /// </summary>
        public static string CheckProtocolEmailStatusError {
            get {
                return ResourceManager.GetString("CheckProtocolEmailStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non hai credenziali salvate.
        /// </summary>
        public static string CredentialNotFound {
            get {
                return ResourceManager.GetString("CredentialNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il processo diassociazione di un documento al documento capofila specificato..
        /// </summary>
        public static string DocumentNotGrouped {
            get {
                return ResourceManager.GetString("DocumentNotGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il documento non è stato firmato perché non è nello stato di firma necessaria..
        /// </summary>
        public static string DocumentSignFailed {
            get {
                return ResourceManager.GetString("DocumentSignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il documento non è stato ancora firmato..
        /// </summary>
        public static string DocumentToSign {
            get {
                return ResourceManager.GetString("DocumentToSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il driver è già presente per la licenza specificata..
        /// </summary>
        public static string DriverAlreadyExists {
            get {
                return ResourceManager.GetString("DriverAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specificare o la risorsa esterna o lo stream dati.
        /// </summary>
        public static string ExternalAndFile {
            get {
                return ResourceManager.GetString("ExternalAndFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile recuperare file esterni.
        /// </summary>
        public static string ExternalFile {
            get {
                return ResourceManager.GetString("ExternalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un tassista in gestione economica può essere associato a massimo n. {0} licenze attive.
        /// </summary>
        public static string FALicenseeNumTresholdExceeded {
            get {
                return ResourceManager.GetString("FALicenseeNumTresholdExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È obbligatorio caricare un file .docx.
        /// </summary>
        public static string FileIsMandatory {
            get {
                return ResourceManager.GetString("FileIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specificare il nome file con la risorsa esterna.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutte le anagrafiche inserite devono far riferimento a persone fisiche.
        /// </summary>
        public static string FinancialAdministrationDriversMustBeTaxi {
            get {
                return ResourceManager.GetString("FinancialAdministrationDriversMustBeTaxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;anagrafica della gestione economica deve essere una persona giuridica.
        /// </summary>
        public static string FinancialAdministrationMustBeLegalPerson {
            get {
                return ResourceManager.GetString("FinancialAdministrationMustBeLegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non possono essere associate più gestioni economiche alla licenza.
        /// </summary>
        public static string FinancialAdministrationNotAdded {
            get {
                return ResourceManager.GetString("FinancialAdministrationNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione economica non trovata.
        /// </summary>
        public static string FinancialAdministrationNotFound {
            get {
                return ResourceManager.GetString("FinancialAdministrationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il processo di rilascio di un documento..
        /// </summary>
        public static string InChargeOfTheFolderNotReleased {
            get {
                return ResourceManager.GetString("InChargeOfTheFolderNotReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il formato del file inserito non è valido. Sono ammessi solo file di tipo .docx..
        /// </summary>
        public static string InvalidAttachmentExtension {
            get {
                return ResourceManager.GetString("InvalidAttachmentExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Fiscale/Partita IVA non valido/a..
        /// </summary>
        public static string InvalidFiscalCodeOrVATNumber {
            get {
                return ResourceManager.GetString("InvalidFiscalCodeOrVATNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile riconoscere la tipologia di individuo..
        /// </summary>
        public static string InvalidIndividualCast {
            get {
                return ResourceManager.GetString("InvalidIndividualCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La licenza può essere creata solo con i seguenti stati: &apos;{0}&apos;, &apos;{1}&apos;.
        /// </summary>
        public static string InvalidInitialState {
            get {
                return ResourceManager.GetString("InvalidInitialState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questa transazione di stato non è valida.
        /// </summary>
        public static string InvalidLicenseeStateTransition {
            get {
                return ResourceManager.GetString("InvalidLicenseeStateTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile aggiungere il proprietario in quanto lo è già della licenza {0}, bisogna attivare la gestione economica..
        /// </summary>
        public static string InvalidNccOwner {
            get {
                return ResourceManager.GetString("InvalidNccOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operazione non consentita per lo stato attuale della richiesta..
        /// </summary>
        public static string InvalidRequestStatus {
            get {
                return ResourceManager.GetString("InvalidRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il sottoturno specificato non fa parte del turno selezionato..
        /// </summary>
        public static string InvalidSubShift {
            get {
                return ResourceManager.GetString("InvalidSubShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuo giuridico non trovato.
        /// </summary>
        public static string LegalPersonNotFound {
            get {
                return ResourceManager.GetString("LegalPersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenza già presente con stesso numero.
        /// </summary>
        public static string LicenseeAlredyExist {
            get {
                return ResourceManager.GetString("LicenseeAlredyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&apos; possibile fare solo variazioni di entità collegate ad una licenza (usare la funzione di edit).
        /// </summary>
        public static string LicenseeControlVariation {
            get {
                return ResourceManager.GetString("LicenseeControlVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Può esserci massimo n. {0} collaboratori per licenza.
        /// </summary>
        public static string LicenseeFamilyCollaborationNumTresholdExceeded {
            get {
                return ResourceManager.GetString("LicenseeFamilyCollaborationNumTresholdExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La licenza risulta terminata o sospesa.
        /// </summary>
        public static string LicenseeInvalidStatus {
            get {
                return ResourceManager.GetString("LicenseeInvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile apportare modifiche ad un licenza cessata.
        /// </summary>
        public static string LicenseeModifyStateError {
            get {
                return ResourceManager.GetString("LicenseeModifyStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenza non trovata.
        /// </summary>
        public static string LicenseeNotFound {
            get {
                return ResourceManager.GetString("LicenseeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente rilascio licenza già presente.
        /// </summary>
        public static string LicenseesIssuingOfficeAlreadyExists {
            get {
                return ResourceManager.GetString("LicenseesIssuingOfficeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ente di rilascio non trovato..
        /// </summary>
        public static string LicenseesIssuingOfficeNotFound {
            get {
                return ResourceManager.GetString("LicenseesIssuingOfficeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile usare una licenza cessata.
        /// </summary>
        public static string LicenseeUseStateError {
            get {
                return ResourceManager.GetString("LicenseeUseStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uno degli indirizzi email non è valido.
        /// </summary>
        public static string MailNotValid {
            get {
                return ResourceManager.GetString("MailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questa licenza è associata a più di un guidatore.
        /// </summary>
        public static string MultipleDriverError {
            get {
                return ResourceManager.GetString("MultipleDriverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non posso variare entità associate a più licenze.
        /// </summary>
        public static string MultipleLicenseeInvalidVariation {
            get {
                return ResourceManager.GetString("MultipleLicenseeInvalidVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile specificare entrambi i tipi di persona fisica e legale.
        /// </summary>
        public static string OnlyOneTypeOfPersonCanBeSpec {
            get {
                return ResourceManager.GetString("OnlyOneTypeOfPersonCanBeSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un proprietario può avere massimo n. {0} licenze attive o sospese.
        /// </summary>
        public static string OwnerLicenseeNumTresholdExceeded {
            get {
                return ResourceManager.GetString("OwnerLicenseeNumTresholdExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile modificare una persona fisica in legale e viceversa.
        /// </summary>
        public static string PersonConversion {
            get {
                return ResourceManager.GetString("PersonConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di individuo non valido..
        /// </summary>
        public static string PersonTypeNotValid {
            get {
                return ResourceManager.GetString("PersonTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il processo di avvio di un procedimento..
        /// </summary>
        public static string ProcessNotStarted {
            get {
                return ResourceManager.GetString("ProcessNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il processo di chiusura di un procedimento..
        /// </summary>
        public static string ProcessNotStopped {
            get {
                return ResourceManager.GetString("ProcessNotStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casella di posta già esistente..
        /// </summary>
        public static string ProtocolEmailAlreadyExists {
            get {
                return ResourceManager.GetString("ProtocolEmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casella di posta non trovata..
        /// </summary>
        public static string ProtocolEmailNotFound {
            get {
                return ResourceManager.GetString("ProtocolEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per rilasciare una licenza bisogna associare una tipoligia di turno.
        /// </summary>
        public static string ReleaseLicenseeShiftError {
            get {
                return ResourceManager.GetString("ReleaseLicenseeShiftError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La richiesta è già presente con stesso numero.
        /// </summary>
        public static string RequestAlreadyExist {
            get {
                return ResourceManager.GetString("RequestAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il dowload del documento..
        /// </summary>
        public static string RequestNotDownloaded {
            get {
                return ResourceManager.GetString("RequestNotDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richiesta non trovata..
        /// </summary>
        public static string RequestNotFound {
            get {
                return ResourceManager.GetString("RequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il processo di protocollazione del documento..
        /// </summary>
        public static string RequestNotProtocol {
            get {
                return ResourceManager.GetString("RequestNotProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il processo di firma del documento..
        /// </summary>
        public static string RequestNotSigned {
            get {
                return ResourceManager.GetString("RequestNotSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il caricamento del documento..
        /// </summary>
        public static string RequestNotUploaded {
            get {
                return ResourceManager.GetString("RequestNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il processo di invio dell&apos;OTP..
        /// </summary>
        public static string RequestOTPNotSended {
            get {
                return ResourceManager.GetString("RequestOTPNotSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il processo di invio del documento protocollato..
        /// </summary>
        public static string RequestProtocolNotSent {
            get {
                return ResourceManager.GetString("RequestProtocolNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non puoi annullare la richiesta di firma di un altro operatore.
        /// </summary>
        public static string RequestRollbackPermission {
            get {
                return ResourceManager.GetString("RequestRollbackPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La richiesta non è nello stato di firma necessaria.
        /// </summary>
        public static string RequestRollbackSignNotRequired {
            get {
                return ResourceManager.GetString("RequestRollbackSignNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La richiesta è già stata firmata.
        /// </summary>
        public static string RequestRollbackSignSigned {
            get {
                return ResourceManager.GetString("RequestRollbackSignSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si è verificato un errore durante il recupero dei documenti..
        /// </summary>
        public static string RequestsNotRetrieved {
            get {
                return ResourceManager.GetString("RequestsNotRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per il turno {0} è necessario specificare un giorno di riposo..
        /// </summary>
        public static string RestDayIsMandatoryForSpecialShift {
            get {
                return ResourceManager.GetString("RestDayIsMandatoryForSpecialShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruolo non trovato.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il turno è in uso su almeno una licenza..
        /// </summary>
        public static string ShiftInUse {
            get {
                return ResourceManager.GetString("ShiftInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specificare data inizio e fine.
        /// </summary>
        public static string StartDateEndDateIsMandatory {
            get {
                return ResourceManager.GetString("StartDateEndDateIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esiste già uno stato di questo tipo con questa descrizione.
        /// </summary>
        public static string StateAlredyExist {
            get {
                return ResourceManager.GetString("StateAlredyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È obbligatorio specificare almeno un sottoturno..
        /// </summary>
        public static string SubShiftIsMandatory {
            get {
                return ResourceManager.GetString("SubShiftIsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il tassista scelto non può effettuare la sostituzione perché è in possesso di una licenza attiva.
        /// </summary>
        public static string SubstituionDriverNotReplaceableActiveLicensee {
            get {
                return ResourceManager.GetString("SubstituionDriverNotReplaceableActiveLicensee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile sostituire un tassista con sé stesso.
        /// </summary>
        public static string SubstituionDriverNotReplaceableWithHimself {
            get {
                return ResourceManager.GetString("SubstituionDriverNotReplaceableWithHimself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esiste già una sostituzione in corso per la licenza indicata.
        /// </summary>
        public static string SubstitutionAlreadyExists {
            get {
                return ResourceManager.GetString("SubstitutionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È già presente una sostituzione in questo range di date.
        /// </summary>
        public static string SubstitutionInvalidDateRange {
            get {
                return ResourceManager.GetString("SubstitutionInvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le licenze NCC non prevedono sostituzioni.
        /// </summary>
        public static string SubstitutionNCCLicensee {
            get {
                return ResourceManager.GetString("SubstitutionNCCLicensee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sostituzione non trovata.
        /// </summary>
        public static string SubstitutionNotFound {
            get {
                return ResourceManager.GetString("SubstitutionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to È possibile esclusivamente cambiare lo stato di una sostituzione da &quot;Terminato&quot; a &quot;Archiviato&quot;.
        /// </summary>
        public static string SubstitutionStatusIsInvalid {
            get {
                return ResourceManager.GetString("SubstitutionStatusIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il tassista selezionato è già associato ad una licenza..
        /// </summary>
        public static string SubstitutionTaxiDriverNotSelectable {
            get {
                return ResourceManager.GetString("SubstitutionTaxiDriverNotSelectable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile aggiungere il tassista perché è stato raggiunto il numero massimo di tassisti per il turno specificato nella licenza..
        /// </summary>
        public static string TaxiDriver_Add_ThresholdExceeded {
            get {
                return ResourceManager.GetString("TaxiDriver_Add_ThresholdExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile aggiungere un tassista fino a quando non viene assegnato un turno alla licenza..
        /// </summary>
        public static string TaxiDriver_SubShiftNotFound {
            get {
                return ResourceManager.GetString("TaxiDriver_SubShiftNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associazione di categoria già presente con stesso codice fiscale e nome.
        /// </summary>
        public static string TaxiDriverAssociationAlredyExist {
            get {
                return ResourceManager.GetString("TaxiDriverAssociationAlredyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;associazione di categoria &apos;{0}&apos; è collegata ad una o più licenze.
        /// </summary>
        public static string TaxiDriverAssociationHaveLicensees {
            get {
                return ResourceManager.GetString("TaxiDriverAssociationHaveLicensees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;associazione di tassisti che si sta tentando di assegnare non esiste..
        /// </summary>
        public static string TaxiDriverAssociationNotFound {
            get {
                return ResourceManager.GetString("TaxiDriverAssociationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tassista non trovato.
        /// </summary>
        public static string TaxiDriverNotFound {
            get {
                return ResourceManager.GetString("TaxiDriverNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il documento non è stato trovato.
        /// </summary>
        public static string Template_TemplateNotFound {
            get {
                return ResourceManager.GetString("Template_TemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esiste già un utente con &apos;{0}&apos; &apos;{1}&apos;..
        /// </summary>
        public static string UserAlredyExist {
            get {
                return ResourceManager.GetString("UserAlredyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente non trovato..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usare la funzione specifica per variare lo stato della licenza.
        /// </summary>
        public static string UseStateEditEndpoin {
            get {
                return ResourceManager.GetString("UseStateEditEndpoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il veicolo esiste già con questa targa.
        /// </summary>
        public static string VehicleAlredyExist {
            get {
                return ResourceManager.GetString("VehicleAlredyExist", resourceCulture);
            }
        }
    }
}
