//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asf.Taxi.BusinessLogic.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Asf.Taxi.BusinessLogic.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accettato.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acronimo.
        /// </summary>
        public static string Acronym {
            get {
                return ResourceManager.GetString("Acronym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attiva.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di allarme.
        /// </summary>
        public static string AllarmType {
            get {
                return ResourceManager.GetString("AllarmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anno.
        /// </summary>
        public static string Annual {
            get {
                return ResourceManager.GetString("Annual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato istanza.
        /// </summary>
        public static string ApplicationState {
            get {
                return ResourceManager.GetString("ApplicationState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo istanza.
        /// </summary>
        public static string ApplicationType {
            get {
                return ResourceManager.GetString("ApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allegato non trovato.
        /// </summary>
        public static string Attachment_NotFound {
            get {
                return ResourceManager.GetString("Attachment_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di nascita.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luogo di nascita.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore massime di pausa.
        /// </summary>
        public static string BreakInHours {
            get {
                return ResourceManager.GetString("BreakInHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata minima di lavoro per usufruire della pausa.
        /// </summary>
        public static string BreakThresholdActivationInHour {
            get {
                return ResourceManager.GetString("BreakThresholdActivationInHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimentazione.
        /// </summary>
        public static string CarFuelType {
            get {
                return ResourceManager.GetString("CarFuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causale.
        /// </summary>
        public static string Causal {
            get {
                return ResourceManager.GetString("Causal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comune.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Documento.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id guidatore.
        /// </summary>
        public static string DriverId {
            get {
                return ResourceManager.GetString("DriverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id guidatore da sostituire.
        /// </summary>
        public static string DriverIdFrom {
            get {
                return ResourceManager.GetString("DriverIdFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id guidatore che sostituisce.
        /// </summary>
        public static string DriverIdTo {
            get {
                return ResourceManager.GetString("DriverIdTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tassisti.
        /// </summary>
        public static string Drivers {
            get {
                return ResourceManager.GetString("Drivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipologia di guidatore.
        /// </summary>
        public static string DriverType {
            get {
                return ResourceManager.GetString("DriverType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero patente.
        /// </summary>
        public static string DrivingLicenceNumber {
            get {
                return ResourceManager.GetString("DrivingLicenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata turno in ore.
        /// </summary>
        public static string DurationInHour {
            get {
                return ResourceManager.GetString("DurationInHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEC.
        /// </summary>
        public static string EmailOrPEC {
            get {
                return ResourceManager.GetString("EmailOrPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato Email/PEC non corretto.
        /// </summary>
        public static string EmailOrPECFormat {
            get {
                return ResourceManager.GetString("EmailOrPECFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data scadenza.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo cessata attività.
        /// </summary>
        public static string ExpireActivityCause {
            get {
                return ResourceManager.GetString("ExpireActivityCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cessata attività.
        /// </summary>
        public static string ExpireActivityDate {
            get {
                return ResourceManager.GetString("ExpireActivityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo orario allarme fiera.
        /// </summary>
        public static string ExpoTimeSlot {
            get {
                return ResourceManager.GetString("ExpoTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path risorsa esterna.
        /// </summary>
        public static string ExternalPath {
            get {
                return ResourceManager.GetString("ExternalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome file.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice fiscale.
        /// </summary>
        public static string FiscalCode {
            get {
                return ResourceManager.GetString("FiscalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato del codice fiscale non corretto.
        /// </summary>
        public static string FiscalCodeFormat {
            get {
                return ResourceManager.GetString("FiscalCodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inizio.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo rimessa.
        /// </summary>
        public static string GarageAddress {
            get {
                return ResourceManager.GetString("GarageAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalità penalizzazione ore dopo della fine del turno.
        /// </summary>
        public static string HandicapAfterInHour {
            get {
                return ResourceManager.GetString("HandicapAfterInHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalità penalizzazione ore prima dell&apos;inizio turno.
        /// </summary>
        public static string HandicapBeforeInHour {
            get {
                return ResourceManager.GetString("HandicapBeforeInHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In uso dal.
        /// </summary>
        public static string InUseSince {
            get {
                return ResourceManager.GetString("InUseSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ruolo non valido..
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turno famigliare.
        /// </summary>
        public static string IsFamily {
            get {
                return ResourceManager.GetString("IsFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborazione familiare.
        /// </summary>
        public static string IsFamilyCollaboration {
            get {
                return ResourceManager.GetString("IsFamilyCollaboration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione economica.
        /// </summary>
        public static string IsFinancialAdministration {
            get {
                return ResourceManager.GetString("IsFinancialAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalità penalizzazione.
        /// </summary>
        public static string IsHandicapMode {
            get {
                return ResourceManager.GetString("IsHandicapMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persona giuridica.
        /// </summary>
        public static string LegalPerson {
            get {
                return ResourceManager.GetString("LegalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id licenza.
        /// </summary>
        public static string LicenseeId {
            get {
                return ResourceManager.GetString("LicenseeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo licenza.
        /// </summary>
        public static string LicenseeType {
            get {
                return ResourceManager.GetString("LicenseeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targa.
        /// </summary>
        public static string LicensePlate {
            get {
                return ResourceManager.GetString("LicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo sanzione.
        /// </summary>
        public static string MeasureType {
            get {
                return ResourceManager.GetString("MeasureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id tipo sanzione.
        /// </summary>
        public static string MeasureTypeId {
            get {
                return ResourceManager.GetString("MeasureTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MimeType.
        /// </summary>
        public static string MimeType {
            get {
                return ResourceManager.GetString("MimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modello.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragione sociale.
        /// </summary>
        public static string Nominative {
            get {
                return ResourceManager.GetString("Nominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id titolare.
        /// </summary>
        public static string OwnerId {
            get {
                return ResourceManager.GetString("OwnerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id persona.
        /// </summary>
        public static string PersonId {
            get {
                return ResourceManager.GetString("PersonId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di telefono.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato del numero di telefono non corretto.
        /// </summary>
        public static string PhoneNumberFormat {
            get {
                return ResourceManager.GetString("PhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAP.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data protocollo.
        /// </summary>
        public static string ProtocolDate {
            get {
                return ResourceManager.GetString("ProtocolDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero protocollo.
        /// </summary>
        public static string ProtocolNumber {
            get {
                return ResourceManager.GetString("ProtocolNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinatario.
        /// </summary>
        public static string Recipient {
            get {
                return ResourceManager.GetString("Recipient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riferimento.
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motivo rifiuto.
        /// </summary>
        public static string RejectReason {
            get {
                return ResourceManager.GetString("RejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data rilascio.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilasciata da.
        /// </summary>
        public static string ReleasedBy {
            get {
                return ResourceManager.GetString("ReleasedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Richiesta.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato richiesta.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo richiesta.
        /// </summary>
        public static string RequestType {
            get {
                return ResourceManager.GetString("RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giorno di riposo.
        /// </summary>
        public static string RestDay {
            get {
                return ResourceManager.GetString("RestDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequenza giorni di lavoro prima del giorno di riposo.
        /// </summary>
        public static string RestDayFrequencyInDays {
            get {
                return ResourceManager.GetString("RestDayFrequencyInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regole.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orario inizio turno.
        /// </summary>
        public static string ShiftStarts {
            get {
                return ResourceManager.GetString("ShiftStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato orario del turno non corretto.
        /// </summary>
        public static string ShiftStartsFormat {
            get {
                return ResourceManager.GetString("ShiftStartsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo turno.
        /// </summary>
        public static string ShiftType {
            get {
                return ResourceManager.GetString("ShiftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inizio.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data stato.
        /// </summary>
        public static string StateDate {
            get {
                return ResourceManager.GetString("StateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione stato.
        /// </summary>
        public static string StateDescription {
            get {
                return ResourceManager.GetString("StateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id stato.
        /// </summary>
        public static string StateId {
            get {
                return ResourceManager.GetString("StateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo stato.
        /// </summary>
        public static string StateType {
            get {
                return ResourceManager.GetString("StateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oggetto.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sottoturni.
        /// </summary>
        public static string SubShifts {
            get {
                return ResourceManager.GetString("SubShifts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo sottoturno.
        /// </summary>
        public static string SubShiftType {
            get {
                return ResourceManager.GetString("SubShiftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fine sostituzione.
        /// </summary>
        public static string SubstitutionEndDate {
            get {
                return ResourceManager.GetString("SubstitutionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data inizio sostituzione.
        /// </summary>
        public static string SubstitutionStartDate {
            get {
                return ResourceManager.GetString("SubstitutionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id associazione di categoria.
        /// </summary>
        public static string TaxiDriverAssociationId {
            get {
                return ResourceManager.GetString("TaxiDriverAssociationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spezzato fiera.
        /// </summary>
        public static string TimeSlotType_ExpoWithPause {
            get {
                return ResourceManager.GetString("TimeSlotType_ExpoWithPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libero.
        /// </summary>
        public static string TimeSlotType_Free {
            get {
                return ResourceManager.GetString("TimeSlotType_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preassegnato.
        /// </summary>
        public static string TimeSlotType_PreAllocated {
            get {
                return ResourceManager.GetString("TimeSlotType_PreAllocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orario.
        /// </summary>
        public static string Timestamp {
            get {
                return ResourceManager.GetString("Timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fine.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessaria firma del dirigente.
        /// </summary>
        public static string ToSignByAdmin {
            get {
                return ResourceManager.GetString("ToSignByAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente già esistente..
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data validità.
        /// </summary>
        public static string ValidityDate {
            get {
                return ResourceManager.GetString("ValidityDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note sulla variazione.
        /// </summary>
        public static string VariationNote {
            get {
                return ResourceManager.GetString("VariationNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partita IVA.
        /// </summary>
        public static string VATNumber {
            get {
                return ResourceManager.GetString("VATNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato della Partita IVA non corretto.
        /// </summary>
        public static string VATNumberFormat {
            get {
                return ResourceManager.GetString("VATNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id veicolo.
        /// </summary>
        public static string VehicleId {
            get {
                return ResourceManager.GetString("VehicleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targa veicolo.
        /// </summary>
        public static string VehicleLicensePlate {
            get {
                return ResourceManager.GetString("VehicleLicensePlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data registrazione veicolo.
        /// </summary>
        public static string VehicleRegistrationDate {
            get {
                return ResourceManager.GetString("VehicleRegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato del Codice di Avviamento Postale non corretto.
        /// </summary>
        public static string ZipCodeFormat {
            get {
                return ResourceManager.GetString("ZipCodeFormat", resourceCulture);
            }
        }
    }
}
