CREATE TABLE [Variation].[Licensees]
(
	[Id] BIGINT IDENTITY (1, 1) NOT NULL,
	[AuthorityId] BIGINT NOT NULL,
	[VariationType] TINYINT NULL,
	[SysStartTime] DATETIME NOT NULL,
	[SysEndTime] DATETIME NOT NULL,
	[Note] VARCHAR(MAX) NULL,
	[LicenseeId] BIGINT NOT NULL,
	[Number] NVARCHAR(64) NULL,
	[ReleaseDate] DATETIME NULL,
	[EndDate] DATETIME NULL,
	[ExpireActivityCause] NVARCHAR(MAX) NULL,
	[ShiftId] BIGINT NULL,
	[SubShiftId] BIGINT NULL,
	[Type] TINYINT NULL,
	[Status] TINYINT NULL,
	[LicenseeNote] NVARCHAR(MAX) NULL,
	[Acronym] VARCHAR(64) NULL,
	[IsFamilyCollaboration] BIT NULL,
	[GarageAddress] VARCHAR(MAX) NULL,
	[IsFinancialAdministration] BIT NULL,
	[FinancialAdministrationId] BIGINT NULL,
	[LicenseesIssuingOfficeId] BIGINT NULL,
	[LicenseesIssuingOfficeDescription] VARCHAR(128) NULL,
	[TaxiDriverAssociationId] BIGINT NULL,
	[TaxiDriverAssociationName] NVARCHAR(MAX),
	[TaxiDriverAssociationFiscalCode] NVARCHAR(64),
	[TaxiDriverId] BIGINT NULL,
	[TaxiDriverFirstName] VARCHAR(128) NULL,
	[TaxiDriverLastName] VARCHAR(MAX) NULL,
	[TaxiDriverFiscalCode] VARCHAR(64) NULL,
	[TaxiDriverType] TINYINT NULL,
	[TaxiDriverPersonType] TINYINT NULL,
	[TaxiDriverShiftStartHour] TINYINT NULL,
	[TaxiDriverShiftStartMinutes] TINYINT NULL,
	[TaxiDriverCollaborationType] TINYINT NULL,
	[VehicleId] BIGINT NULL,
	[VehicleModel] NVARCHAR(256) NULL,
	[VehicleLicensePlate] VARCHAR(16) NULL,
	[VehicleRegistrationDate] DATETIME NULL,
	[VehicleCarFuelType] TINYINT NULL,
	[VehicleInUseSince] DATETIME NULL,
	[FolderId] UNIQUEIDENTIFIER NULL,
	CONSTRAINT [PK_LicenseesNew] PRIMARY KEY Clustered ([Id] ASC),
	CONSTRAINT [FK_LicenseeVariations_Licensees] FOREIGN KEY ([LicenseeId]) REFERENCES [Taxi].[Licensees] ([Id])
)
